### ISSUE TITLE
Errors messages not showing on login and register

### ISSUE THREAD

**Issue by NSpehler** [andranikbadalyan/Laravel-Passport-Vue-Auth#1]
Hello Andranik,

Thank you for this great implementation of Vue + Laravel Passport.

Everything works great except the error messages that are not showing when entering a wrong login or an invalid password confirmation during registration. The problem is also visible on your demo page.

It seems the 422 error is thrown, but VueX fails to store the error messages.

<img width="495" alt="screenshot 2018-08-18 11 21 39" src="https://user-images.githubusercontent.com/379186/44297852-ec8b7c00-a2d8-11e8-9938-e62bac63096e.png">

<img width="642" alt="screenshot 2018-08-18 11 21 54" src="https://user-images.githubusercontent.com/379186/44297853-ef866c80-a2d8-11e8-9e2b-79d3d48633cd.png">

What do you think is the best way to address this?

Thanks,
Nicolas

**Comment by andranikbadalyan** [comment]
Hey Nicolas, thanks for bringing this to my attention. You're right it's not storing the error message, I'll fix it later today or tomorrow.

**Comment by NSpehler** [comment]
That would be awesome! Thanks a whole lot.

**Comment by oliverbj** [comment]
@NSpehler Were you able to install this and login using the default credentials? I am unable to login after following the installation steps.

**Comment by andranikbadalyan** [comment]
did you copy paste the oAuth token in .env file?

**Comment by NSpehler** [comment]
Hello Andranik,

Thank you for the update, errors are now showing on a failed login.

However, I'm afraid the errors are still not showing during registration. If you try entering a wrong `password_confirmation` for example, the 422 is returned from the server-side but not appearing on the form.

<img width="657" alt="screenshot 2018-08-21 23 31 54" src="https://user-images.githubusercontent.com/379186/44430434-f17f5280-a59a-11e8-885f-a9eaafc54d9f.png">

Thanks,
Nicolas

**Comment by andranikbadalyan** [comment]
hmm...seems like register returns "errors" and login returns "error", I'll keep you posted once I fix this

**Comment by oliverbj** [comment]
Hey @andranikbadalyan  any news on this? I've tried to fix it myself, but without luck. Cannot seem to locate where the error is being triggered.

**Comment by andranikbadalyan** [comment]
the only time we get error is during failed login, so I just added the following line to the auth.js

let errors=err.errors?err.errors:{};
if(err.error=="invalid_credentials"){
    errors.invalid_credentials=['The user credentials were incorrect.'];
}

**Comment by NSpehler** [comment]
What about register? 😇

**Comment by andranikbadalyan** [comment]
Register sends back "errors" (which should be working fine as well now)

**Comment by NSpehler** [comment]
Awesome, it's working! Thanks a lot! 🎉
