### ISSUE TITLE
Wrong login credentials

### ISSUE THREAD

**Issue by oliverbj** [andranikbadalyan/Laravel-Passport-Vue-Auth#2]
Very nice starter project indeed! I have followed the steps to install this, but I am not able to login. I get the following error: "The user credentials were incorrect."

**Comment by andranikbadalyan** [comment]
Thank you, make sure after you run "php artisan passport:install" to copy the 2nd secret in .env file as VUE_CLIENT_ID. If that's doesn't fix it run "php artisan config:clear" and refresh your browser. Also make sure you have seeded the user in your table when migrating.

**Comment by andranikbadalyan** [comment]
I just realized I was hard-coding the encrypted password in the seeder, that was most likely the issue.

**Comment by oliverbj** [comment]
Yes, followed all the steps. 
I just checked the seeder file and saw this `$user->password =  bcrypt('secret');`. Should I change this in order to get it to work?
Appreciate the work!

**Comment by oliverbj** [comment]
Ah sorry, just saw you edited the seeder to include the bcrypt function. However, I made a fresh install and is still not able to login using the standard credentials. This is my console log when submitting the form:

![test](https://user-images.githubusercontent.com/7851696/44423402-57151400-a586-11e8-8bb7-9cb0218a69b7.png)

**Comment by oliverbj** [comment]
Just made a FRESH install again, and it finally worked. I believe that I copied the first client secret from the passport into the .env file, and not the 2nd like you said. (Maybe this should be updated in the readme file?)

**Comment by andranikbadalyan** [comment]
in your database you should have oauth_clients table, it should have 2 rows:
1. Personal Access Client
2. Password Grant Client

copy the "secret" field from the 2nd row (Password Grant) to .env VUE_CLIENT_SECRET
VUE_CLIENT_ID=2
VUE_CLIENT_SECRET=

this should work

**Comment by andranikbadalyan** [comment]
:) glad to hear it worked

**Comment by oliverbj** [comment]
Thanks for this starter package, really appreciate it! Will work on expanding it.
