### ISSUE TITLE
Access tokens

### ISSUE THREAD

**Issue by oliverbj** [andranikbadalyan/Laravel-Passport-Vue-Auth#3]
Hi there
I just tested a bit further on this package, and noticed that it creates a new token in `oath_access_token` and in `oauth_refresh_tokens` whenever I sign in.

Having a lot of users, these two tables will quickly be swamped with a lot of different access tokens. Is there a way around this?

**Comment by andranikbadalyan** [comment]
I'm thinking either revoke the old token when the new one is issued, but in that case if someone is using multiple devices it'll kick them out of all the other devices. I think the more logical thing would be to add a cron job (laravel task schedule) to clean up the expired tokens and maybe decrease the lifetime of the token.

If you have a more elegant suggestion let me know, but meanwhile I'll try to work on the cron job option.

**Comment by oliverbj** [comment]
I agree that revoking the old, when a new one is issued would create problems with multiple devices.

I know that you can clear the password resets tokens by using the command `php artisan auth:clear-resets` - so maybe a command which does the same for the expired tokens? We can then set the command up using `Task Scheduler` to run it eg. once a week?

**Comment by andranikbadalyan** [comment]
Instead of revoking the logged out tokens, I just changed it to be deleted when you log out. FYI if you login from multiple devices you'll have a new token for each one.
