### ISSUE TITLE
Using Passport for tokens/clients

### ISSUE THREAD

**Issue by oliverbj** [andranikbadalyan/Laravel-Passport-Vue-Auth#4]
After installing this, I can successfully login my SPA. But I then want to be able to administer tokens, to issue to 3rd party applications. To do this, I follow the official documentation for [Laravel Passport][2].

I've registered the Vue components as mentioned in the documentation, and they also do show up in my app. However, for some reason they contain a lot of "empty" clients and tokens:

[![Empty Clients][3]][3]

[![Empty Tokens][4]][4]

Checking my console, I see that I can't even access the `/oauth/*`:

[![Errors][5]][5]

This is my `AuthServiceProvider.php`:

    public function boot()
    {
        $this->registerPolicies();
    
        Passport::routes(function ($router) {
            $router->forAccessTokens();
        });
    }

This is my `routes/api.php`:

    Route::middleware('auth:api')->group(function () {
        Route::get('/user', function (Request $request) {
            return $request->user();
        });
    });

*Please note, I can successfully log in / out of the "main" application. I just can't create new clients/tokens, so I can access my API from other applications.*

  [1]: https://github.com/andranikbadalyan/Laravel-Passport-Vue-Auth
  [2]: https://laravel.com/docs/5.6/passport#frontend-quickstart
  [3]: https://i.stack.imgur.com/JrcDN.png
  [4]: https://i.stack.imgur.com/WokCK.png
  [5]: https://i.stack.imgur.com/mr82b.png

**Comment by andranikbadalyan** [comment]
Hey, if you want to use the full oauth functionality of passport remove the following lines from AuthServiceProvider.php

    Passport::routes(function ($router) {
        $router->forAccessTokens();
    });

and replace it with

   Passport::routes();

**Comment by oliverbj** [comment]
Above fixes the empty rows, however I still get 401 Unauthorized.

**Comment by andranikbadalyan** [comment]
I see what the problem is, all of these routes use web Middleware to make sure you are authenticated, which is a session based authentication. I guess to use all the functionality we'll have to covert all of these routes to use auth:api authentication

![capture](https://user-images.githubusercontent.com/7595988/44738765-cd47d800-aaaa-11e8-9567-b5e388d6127d.JPG)

**Comment by oliverbj** [comment]
Ah yes, and that's the reason for the 401. Any idea on how to still be able to consume the Passport functions using this repo?

**Comment by andranikbadalyan** [comment]
change the middleware on the routes to auth:api, but you'll have to give me some time to get this done.

**Comment by oliverbj** [comment]
No problem, really appreciate your help!! This is going to be pretty awesome

**Comment by andranikbadalyan** [comment]
I just updated the routes, pretty sure it'll work but haven't really tested yet. Please let me know if the routes are authenticated now.

Thanks!

**Comment by oliverbj** [comment]
Wow! Almost got it working, however when I try to create a new personal token, I get a 500 Internal Server Error:

```
    "message": "Trying to get property 'id' of non-object",
    "exception": "ErrorException",
    "file": "/Users/oliverbusk/Sites/spa/vendor/laravel/passport/src/PersonalAccessTokenFactory.php",
    "line": 98,
```

This is line 98 in above file:

`'client_id' => $client->id,`

**Comment by oliverbj** [comment]
Please note that I can create clients without any problems - it's just personal access tokens, where I get above error.

**Comment by andranikbadalyan** [comment]
I just tested it on mine, works fine. I think you need to regenerate your keys.
php artisan passport:install --force

**Comment by andranikbadalyan** [comment]
just updated the demo to use the full passport functionality there, check it out:
https://www.andranikbadalyan.com/laravelpassportvueauth/
user: andranikvbadalyan@gmail.com
pass: secret

**Comment by oliverbj** [comment]
Wonderful!! Just did the `php artisan passport:install --force` - works like a charm! Thanks!!
